################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Src/MQTT_fundamental.c \
../Core/Src/TLS_fundamental.c \
../Core/Src/connection_fundamental.c \
../Core/Src/dfsdm.c \
../Core/Src/eeprom_emul.c \
../Core/Src/gpio.c \
../Core/Src/i2c.c \
../Core/Src/main.c \
../Core/Src/quadspi.c \
../Core/Src/rng.c \
../Core/Src/rtc.c \
../Core/Src/spi.c \
../Core/Src/stm32l4xx_hal_msp.c \
../Core/Src/stm32l4xx_it.c \
../Core/Src/syscalls.c \
../Core/Src/sysmem.c \
../Core/Src/system_stm32l4xx.c \
../Core/Src/tim.c \
../Core/Src/usart.c \
../Core/Src/usb_otg.c 

C_DEPS += \
./Core/Src/MQTT_fundamental.d \
./Core/Src/TLS_fundamental.d \
./Core/Src/connection_fundamental.d \
./Core/Src/dfsdm.d \
./Core/Src/eeprom_emul.d \
./Core/Src/gpio.d \
./Core/Src/i2c.d \
./Core/Src/main.d \
./Core/Src/quadspi.d \
./Core/Src/rng.d \
./Core/Src/rtc.d \
./Core/Src/spi.d \
./Core/Src/stm32l4xx_hal_msp.d \
./Core/Src/stm32l4xx_it.d \
./Core/Src/syscalls.d \
./Core/Src/sysmem.d \
./Core/Src/system_stm32l4xx.d \
./Core/Src/tim.d \
./Core/Src/usart.d \
./Core/Src/usb_otg.d 

OBJS += \
./Core/Src/MQTT_fundamental.o \
./Core/Src/TLS_fundamental.o \
./Core/Src/connection_fundamental.o \
./Core/Src/dfsdm.o \
./Core/Src/eeprom_emul.o \
./Core/Src/gpio.o \
./Core/Src/i2c.o \
./Core/Src/main.o \
./Core/Src/quadspi.o \
./Core/Src/rng.o \
./Core/Src/rtc.o \
./Core/Src/spi.o \
./Core/Src/stm32l4xx_hal_msp.o \
./Core/Src/stm32l4xx_it.o \
./Core/Src/syscalls.o \
./Core/Src/sysmem.o \
./Core/Src/system_stm32l4xx.o \
./Core/Src/tim.o \
./Core/Src/usart.o \
./Core/Src/usb_otg.o 


# Each subdirectory must supply rules for building sources it contributes
Core/Src/MQTT_fundamental.o: ../Core/Src/MQTT_fundamental.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/MQTT_fundamental.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/TLS_fundamental.o: ../Core/Src/TLS_fundamental.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/TLS_fundamental.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/connection_fundamental.o: ../Core/Src/connection_fundamental.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/connection_fundamental.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/dfsdm.o: ../Core/Src/dfsdm.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/dfsdm.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/eeprom_emul.o: ../Core/Src/eeprom_emul.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/eeprom_emul.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/gpio.o: ../Core/Src/gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/i2c.o: ../Core/Src/i2c.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/i2c.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/main.o: ../Core/Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/quadspi.o: ../Core/Src/quadspi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/quadspi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/rng.o: ../Core/Src/rng.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/rng.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/rtc.o: ../Core/Src/rtc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/rtc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/spi.o: ../Core/Src/spi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/spi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32l4xx_hal_msp.o: ../Core/Src/stm32l4xx_hal_msp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32l4xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32l4xx_it.o: ../Core/Src/stm32l4xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32l4xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/syscalls.o: ../Core/Src/syscalls.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/syscalls.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/sysmem.o: ../Core/Src/sysmem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/sysmem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/system_stm32l4xx.o: ../Core/Src/system_stm32l4xx.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/system_stm32l4xx.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/tim.o: ../Core/Src/tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/usart.o: ../Core/Src/usart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/usart.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/usb_otg.o: ../Core/Src/usb_otg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/CMSIS/Device/ST/STM32L4xx/Source/Templates" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/wifi_Src" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/mbedtls" -I"C:/Users/39389/Desktop/PLEINAIR/Pleinair/Core/lib/MQTT_Inc" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/usb_otg.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

